[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myproject"
version = "0.1.0"
dependencies = [
    "pandas"
]

[tool.split]
valid_size = 20
test_size = 10
# train_size = 100 - (test_size + valid_size)